### ISSUE TITLE
Hi,sir! How to switch to the dark mode?

### ISSUE THREAD

**Issue by andersling** [plutobell/pi-dashboard-go#4]
Thanks for your greate job! but one question: How to switch to the dark mode of the UI? 

Thanks!

**Comment by plutobell** [comment]
> Thanks for your greate job! but one question: How to switch to the dark mode of the UI?
> 
> Thanks!

Hi ,there.
It automatically switches with the system display mode. maybe in the next version a manual switch method will be added.

**Comment by plutobell** [comment]
> Thanks for your greate job! but one question: How to switch to the dark mode of the UI?
> 
> Thanks!

[v1.7.0](https://github.com/plutobell/pi-dashboard-go/releases/tag/v1.7.0) now available.
